pom.xml, src/main/java/org/jsmart/zerocode/core/httpclient/ssl/SslTrustHttpClient.java, src/main/resources/01_verification_test_cases/21_ssl_trust.json, src/test/java/org/jsmart/zerocode/core/verification/SslTrustUseHttpClientTest.java
Dear Author, 
please review, approve n merge if possible. 
Regards, 
Sameer
=> ISSUE-14 # Fixed. SSL Auto trusted for CustoHttpClient

pom.xml, src/test/java/org/jsmart/zerocode/core/tests/H2DBTest.java
=> H2 db maven entry and db test

pom.xml, src/main/java/org/jsmart/zerocode/core/domain/ReportProperties.java, src/main/java/org/jsmart/zerocode/core/domain/builders/ExtentReportsFactory.java, src/main/java/org/jsmart/zerocode/core/domain/builders/ZeroCodeChartKeyValueArrayBuilder.java, src/main/java/org/jsmart/zerocode/core/domain/builders/ZeroCodeChartKeyValueBuilder.java, src/main/java/org/jsmart/zerocode/core/domain/reports/ZeroCodeReportProperties.java, src/main/java/org/jsmart/zerocode/core/domain/reports/chart/ZeroCodeChartKeyValue.java, src/main/java/org/jsmart/zerocode/core/engine/listener/ZeroCodeTestReportListener.java, src/main/java/org/jsmart/zerocode/core/logbuilder/LogCorrelationshipPrinter.java, src/main/java/org/jsmart/zerocode/core/report/ZeroCodeReportGenerator.java, src/main/java/org/jsmart/zerocode/core/report/ZeroCodeReportGeneratorImpl.java, src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeUnitRunner.java, src/main/resources/reports/01_high_chart_column.vm, src/test/java/org/jsmart/zerocode/core/domain/reports/chart/ZeroCodeChartKeyValueTest.java, src/test/java/org/jsmart/zerocode/core/report/ZeroCodeReportGeneratorImplTest.java, src/test/resources/soap_host.properties
- And Dashboard etc fancy stuff
=> ISSUE-43 # Red Spike, Interactive report - Filter by group or author

src/main/java/org/jsmart/zerocode/core/httpclient/BasicHttpClient.java, src/main/java/org/jsmart/zerocode/core/httpclient/utils/FileUploadUtils.java, src/test/java/org/jsmart/zerocode/core/httpclient/BasicHttpClientTest.java
Fixes #168 , also added adequate tests to verify the fix. I am open for suggestions.
=> ISS-168 # multipart/form-data support without file

.gitignore, .travis.yml, src/test/java/org/jsmart/zerocode/kafka/consume/KafkaConsumeTest.java, src/test/java/org/jsmart/zerocode/kafka/customclient/KafkaProduceCustomClientTest.java, src/test/java/org/jsmart/zerocode/kafka/produce/KafkaProduceTest.java
Configured single node Kafka for Travis CI.  Refer #151 
[Travis Job](https://travis-ci.org/authorjapps/zerocode/jobs/472276537)
**_Note_**: Still few enhancements can be done. But it is not blocking. Everything works as expected.
=> ISS-151 Kafka for CI

README.md, src/main/java/org/jsmart/zerocode/core/di/main/ApplicationMainModule.java, src/main/java/org/jsmart/zerocode/core/di/module/PropertiesInjectorModule.java, src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeJsonTestProcesorImpl.java, src/main/java/org/jsmart/zerocode/core/kafka/consume/ConsumerLocalConfigs.java, src/main/java/org/jsmart/zerocode/core/kafka/helper/KafkaConsumerHelper.java, src/main/java/org/jsmart/zerocode/core/kafka/receive/ConsumerCommonConfigs.java, src/main/java/org/jsmart/zerocode/core/kafka/receive/KafkaReceiver.java, src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeUnitRunner.java, src/test/java/org/jsmart/zerocode/core/engine/ConfigTest.java, src/test/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeJsonTestProcesorImplTest.java, src/test/java/org/jsmart/zerocode/core/kafka/consume/ConsumerLocalConfigsWrapTest.java, src/test/java/org/jsmart/zerocode/core/kafka/helper/KafkaConsumerHelperTest.java, src/test/java/org/jsmart/zerocode/core/tests/customrunner/SimulatorState.java, src/test/java/org/jsmart/zerocode/core/tests/customrunner/TestOnlyZeroCodePackageRunner.java, src/test/java/org/jsmart/zerocode/core/tests/customrunner/TestOnlyZeroCodeUnitRunner.java, src/test/java/org/jsmart/zerocode/core/verification/hostproperties/PropertiesInStepsPackageRunnerTest.java, src/test/java/org/jsmart/zerocode/core/verification/hostproperties/PropertiesInStepsUnitRunnerTest.java, src/test/java/org/jsmart/zerocode/kafka/KafkaSuite.java, src/test/java/org/jsmart/zerocode/kafka/consume/KafkaConsumeSeekOffsetTest.java, src/test/resources/dev_test.properties, src/test/resources/host_keys/property_reading_into_test_step_test.json, src/test/resources/kafka/consume/test_kafka_consume_seek_offset.json
Ticket https://github.com/authorjapps/zerocode/issues/183
=> ISS-183 - Properties file Key Value in Test steps

core/pom.xml, kafka-testing/src/test/java/org/jsmart/zerocode/integration/tests/kafka/consume/KafkaConsumeAvroTest.java, kafka-testing/src/test/java/org/jsmart/zerocode/integration/tests/kafka/consume/negative/KafkaConsumeAvroNegativeTest.java, pom.xml
- Can be added manually to make the tests Pass
=> ISS-199 # [On User Demand] POM - Removed Confluent Avro dependency

core/src/main/java/org/jsmart/zerocode/core/domain/builders/ExtentReportsFactory.java, core/src/main/java/org/jsmart/zerocode/core/logbuilder/LogCorrelationshipPrinter.java, core/src/main/java/org/jsmart/zerocode/core/logbuilder/ResponseLogBuilder.java, core/src/main/java/org/jsmart/zerocode/core/report/ZeroCodeReportGeneratorImpl.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImpl.java, core/src/test/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImplE2ETest.java, http-testing/src/test/resources/wiremock_tests/soap_mocking_via_wiremock_test.json, pom.xml
Fixes #52 
More info can be found in the issue thread.
=> ISS 52 report enhancement

core/src/main/java/org/jsmart/zerocode/core/engine/mocker/RestEndPointMocker.java, core/src/test/java/org/jsmart/zerocode/core/engine/mocker/RestEndPointMockerTest.java, core/src/test/resources/wiremock_integration/wiremock_end_point_json_body.json
Added Content-type in the mock response, if it is specified
=> Added Content-type in the mock response, if it is specified

CONTRIBUTING.md
=> ISS-261 # Fixed typo in CONTRIBUTING.md

README.md, core/src/main/java/org/jsmart/zerocode/core/domain/Scenario.java, core/src/main/java/org/jsmart/zerocode/core/domain/Scenarios.java, core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ScenarioExecutionState.java, core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/StepExecutionState.java, core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeExternalFileProcessor.java, core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeExternalFileProcessorImpl.java, core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeJsonTestProcesor.java, core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeJsonTestProcesorImpl.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImpl.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodePackageRunner.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeUnitRunner.java, core/src/test/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeJsonTestProcesorImplTest.java, core/src/test/java/org/jsmart/zerocode/core/runner/ZeroCodePackageRunnerScenariosTest.java, core/src/test/java/org/jsmart/zerocode/core/scenario/ScenarioAnnotationTest.java, http-testing/src/test/java/org/jsmart/zerocode/testhelp/tests/helloworld/JustHelloWorldTest.java
Final bit in WIP_(In Progress) in this PR, but you can start reviewing...
=> ISS-258 # Support Scenario annotation(low priority - user request)

core/src/main/java/org/jsmart/zerocode/converter/Converter.java, core/src/main/java/org/jsmart/zerocode/converter/MimeTypeConverter.java, core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeJsonTestProcesorImpl.java, core/src/test/java/org/jsmart/zerocode/converter/MimeTypeConverterTest.java, core/src/test/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeJsonTestProcesorImplTest.java, http-testing/src/main/java/org/jsmart/zerocode/zerocodejavaexec/DbSqlExecutor.java, http-testing/src/test/java/org/jsmart/zerocode/testhelp/tests/helloworldarrayelementmatching/HelloWorldArrayElementPickerTest.java, http-testing/src/test/resources/helloworld_array_dynamic_element/dynamic_array_element_picker_test.json
- Even for single matching element
=> ISS-16 # [HelloWorld repo] When Json Path returns array

README.md, images/jetbrains.svg
Worked on #284 
Let me know your comments for further improvements.
=> Added credits to Jetbrains

core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeTokens.java, core/src/main/java/org/jsmart/zerocode/core/utils/TokenUtils.java, core/src/test/java/org/jsmart/zerocode/core/utils/TokenUtilsTest.java, http-testing/src/test/resources/helloworld_token_resolving/helloworld_token_resolving_ok.json
Implements #282 Ability to resolve environment variables in JSON steps.
=> Ability to resolve environment variables in JSON steps

core/pom.xml, core/src/main/java/org/jsmart/zerocode/core/di/module/ObjectMapperModule.java, core/src/main/java/org/jsmart/zerocode/core/di/provider/YamlObjectMapperProvider.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodePackageRunner.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeUnitRunner.java, core/src/main/java/org/jsmart/zerocode/core/utils/SmartUtils.java, core/src/test/java/org/jsmart/zerocode/core/domain/yaml/YamlParsingTest.java, core/src/test/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeAssertionsProcessorImplTest.java, core/src/test/java/org/jsmart/zerocode/core/utils/SmartUtilsTest.java, core/src/test/java/org/jsmart/zerocode/core/yaml/YamlApiIntegrationTest.java, core/src/test/resources/integration_test_files/yaml/simple_get_api_multi_step_test.yml, core/src/test/resources/integration_test_files/yaml/simple_get_api_test.yml, core/src/test/resources/integration_test_files/yaml/string_optional_double_quotes_test.yml, core/src/test/resources/unit_test_files/yaml/scenario_get_api_test.yml, pom.xml
- Basic flow tested
- Optional DOuble Quoted String tested
- Json Path for Req and resp tested
=> ISS-277 # YAML Scenario DSL - Unit and Integration

core/src/main/java/org/jsmart/zerocode/core/domain/builders/ExtentReportsFactory.java, core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeAssertionsProcessorImpl.java, core/src/main/java/org/jsmart/zerocode/core/utils/FieldTypeConversionUtils.java, core/src/test/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeAssertionsProcessorImplTest.java, core/src/test/java/org/jsmart/zerocode/core/utils/FieldTypeConversionUtilsTest.java, core/src/test/java/org/jsmart/zerocode/parameterized/ParameterizedDemoTypeCastTest.java, core/src/test/java/org/jsmart/zerocode/typecast/TypeCastIntegrationTest.java, core/src/test/resources/integration_test_files/parameterized/parameterized_sample_type_cast_test.json, core/src/test/resources/integration_test_files/type_cast/cast_types_to_int_bool_test.json, http-testing/src/test/java/org/jsmart/zerocode/testhelp/tests/helloworldtypecast/HelloWorldTypeCastTest.java, http-testing/src/test/resources/parameterized_csv/hello_world_test_parameterized_csv_type_cast.json
=> ISS-283 and ISS-303 # Type cast feature  and Java vendor -Green

README.md
=> ISS-277 Update README - Post Fix

README.md
I updated README.md to fix some typos and improve its clarity and readability.
=> Updated README.md to fix typos and improve clarity

README.md, core/src/main/java/org/jsmart/zerocode/core/di/main/ApplicationMainModule.java, core/src/main/java/org/jsmart/zerocode/core/domain/Step.java, core/src/main/java/org/jsmart/zerocode/core/domain/Validator.java, core/src/main/java/org/jsmart/zerocode/core/engine/listener/ZeroCodeTestReportListener.java, core/src/main/java/org/jsmart/zerocode/core/engine/validators/ZeroCodeValidator.java, core/src/main/java/org/jsmart/zerocode/core/engine/validators/ZeroCodeValidatorImpl.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImpl.java, core/src/test/java/org/jsmart/zerocode/core/domain/StepTest.java, core/src/test/java/org/jsmart/zerocode/core/domain/ValidatorTest.java, core/src/test/java/org/jsmart/zerocode/core/engine/validators/ZeroCodeValidatorImplTest.java, core/src/test/java/org/jsmart/zerocode/core/utils/SmartUtilsTest.java, core/src/test/java/org/jsmart/zerocode/integrationtests/HelloWorldValidatorsTest.java, core/src/test/resources/integration_test_files/helloworld/get_api_integration_validators_test.json, core/src/test/resources/unit_test_files/engine_unit_test_jsons/00_test_json_single_step_verifications.json, core/src/test/resources/unit_test_files/engine_unit_test_jsons/13_validator_key_value_pair.json, core/src/test/resources/unit_test_files/engine_unit_test_jsons/14_validator_key_value_array.json, core/src/test/resources/unit_test_files/engine_unit_test_jsons/15_test_validators_single_step.json
=> ISS-353 validators help n example in README

core/pom.xml, http-testing/pom.xml, junit5-testing/pom.xml, kafka-testing/pom.xml, pom.xml
=> Zcode sonatype release branch

core/src/main/java/org/jsmart/zerocode/core/engine/tokens/ZeroCodeValueTokens.java, core/src/main/java/org/jsmart/zerocode/core/utils/TokenUtils.java, core/src/test/java/org/jsmart/zerocode/core/utils/TokenUtilsTest.java, core/src/test/resources/unit_test_files/jks_files/dummy_key_store.jks, docker/compose/kafka-single-node.yml, kafka-testing/src/test/java/org/jsmart/zerocode/integration/tests/kafka/consume/KafkaConsumeTest.java, kafka-testing/src/test/resources/security_files/sample_key_store.jks
- On user request(raise an issue)
PR Branch
=> ISS-376 # [ABS.PATH] in Kafka properties

README.md, core/src/main/java/org/jsmart/zerocode/core/domain/Step.java, core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeExternalFileProcessor.java, core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeExternalFileProcessorImpl.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImpl.java, core/src/test/java/org/jsmart/zerocode/integrationtests/MultiStepTest.java, core/src/test/resources/integration_test_files/multi_step/array_step_file_test.json, core/src/test/resources/integration_test_files/multi_step/multi_step_file.json, core/src/test/resources/integration_test_files/multi_step/single_step.json
PR Branch
https://github.com/anishjha93/zerocode/tree/anish_step_files
* [ ✓] Integration tests added?
* [ ✓] Test names are meaningful?
* [ ✓] Feature manually tested?
* [✓ ] Branch build passed?
* [✓ ] No 'package.*' in the imports
=> ISSUE-367 # Multi step support for step file

core/src/main/java/org/jsmart/zerocode/core/domain/builders/ZeroCodeCsvReportBuilder.java, core/src/main/java/org/jsmart/zerocode/core/domain/builders/ZeroCodeReportStepBuilder.java, core/src/main/java/org/jsmart/zerocode/core/domain/reports/ZeroCodeReportStep.java, core/src/main/java/org/jsmart/zerocode/core/domain/reports/csv/ZeroCodeCsvReport.java, core/src/main/java/org/jsmart/zerocode/core/report/ZeroCodeReportGeneratorImpl.java, core/src/test/java/org/jsmart/zerocode/core/domain/reports/ZeroCodeReportTest.java, core/src/test/resources/integration_test_files/helloworld/get_api_integration_test.json
Issue -378 Method details added
PR Branch
=> Issue -378 Method details added

core/src/main/java/org/jsmart/zerocode/core/domain/Step.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImpl.java, core/src/test/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImplVerifyTest.java, core/src/test/resources/integration_test_files/failed_steps_with_ignore/01_two_step_one_fail_and_ignored.json
To write some code using baby step, we should write complete test case (by a PO) and implement it step by step. 
This PR will close #339
=> ISSUE-339 # add ability to ignore some steps

core/src/main/java/org/jsmart/zerocode/core/engine/listener/ZeroCodeTestReportListener.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodePackageRunner.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeUnitRunner.java
=> ISS-00 # Runner and Listener post finished - enhance UX

core/src/main/java/org/jsmart/zerocode/core/domain/reports/ZeroCodeExecResult.java, core/src/main/java/org/jsmart/zerocode/core/domain/reports/ZeroCodeReportStep.java, core/src/main/java/org/jsmart/zerocode/core/report/ZeroCodeReportGeneratorImpl.java, core/src/test/java/org/jsmart/zerocode/core/report/ZeroCodeReportGeneratorImplTest.java
PR Branch
**https://github.com/sparrowV/zerocode**
=> ISSUE-389 # fix retry report issue

core/src/main/java/org/jsmart/zerocode/core/engine/listener/ZeroCodeTestReportListener.java, core/src/main/java/org/jsmart/zerocode/core/httpclient/ssl/SslTrustHttpClient.java, core/src/main/java/org/jsmart/zerocode/core/kafka/client/BasicKafkaClient.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImpl.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodePackageRunner.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeUnitRunner.java, core/src/main/java/org/jsmart/zerocode/core/runner/parallel/LoadProcessor.java, core/src/main/java/org/jsmart/zerocode/core/runner/parallel/ZeroCodeLoadRunner.java, core/src/main/java/org/jsmart/zerocode/core/utils/EnvUtils.java, core/src/main/java/org/jsmart/zerocode/core/utils/RunnerUtils.java, core/src/main/java/org/jsmart/zerocode/parallel/ExecutorServiceRunner.java, core/src/test/java/org/jsmart/zerocode/core/tests/customrunner/TestOnlyZeroCodeUnitRunner.java, core/src/test/java/org/jsmart/zerocode/core/utils/EnvUtilsTest.java, http-testing/src/test/java/org/jsmart/zerocode/testhelp/tests/loadtesting/restendpoint/TestGitGubEndPoint.java, http-testing/src/test/resources/load_config_sample.properties, http-testing/src/test/resources/logback.xml, kafka-testing/src/test/resources/kafka/consume/test_kafka_consume_raw_msg.json
=> Env param values and general improvements

core/src/main/java/org/jsmart/zerocode/core/domain/UseKafkaClient.java
PR Branch
Started understanding the code base, started with the UnitRunnerClass and found this typo.
This commit is to ensure the same is reflected in the javadoc
=> UseKafkaClient @return comment corrected

core/src/main/java/org/jsmart/zerocode/core/utils/FieldTypeConversionUtils.java, core/src/test/java/org/jsmart/zerocode/core/utils/FieldTypeConversionUtilsTest.java
PR Branch
I need it for the project I’m working on.
=> iss-407 FieldTypeConversionUtils add long #407

README.md, core/src/main/java/org/jsmart/zerocode/core/constants/ZeroCodeReportConstants.java, core/src/main/java/org/jsmart/zerocode/core/engine/tokens/ZeroCodeValueTokens.java, core/src/main/java/org/jsmart/zerocode/core/kafka/receive/KafkaReceiver.java, core/src/main/java/org/jsmart/zerocode/core/logbuilder/ZerocodeCorrelationshipLogger.java, core/src/main/java/org/jsmart/zerocode/core/report/ZeroCodeReportGeneratorImpl.java, core/src/main/java/org/jsmart/zerocode/core/runner/StepNotificationHandler.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImpl.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodePackageRunner.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeUnitRunner.java, core/src/main/java/org/jsmart/zerocode/core/runner/parallel/ZeroCodeMultiLoadRunner.java, core/src/main/java/org/jsmart/zerocode/core/utils/RunnerUtils.java, core/src/main/java/org/jsmart/zerocode/core/utils/TokenUtils.java, core/src/test/java/org/jsmart/zerocode/core/report/ZeroCodeReportGeneratorImplTest.java, core/src/test/java/org/jsmart/zerocode/github/TestGitHubApi.java, core/src/test/resources/integration_test_files/soap/soap_request_xml_from_external_xml_file.json, core/src/test/resources/soap_host.properties, kafka-testing/src/test/java/org/jsmart/zerocode/integration/tests/kafka/consume/intercept/KafkaIntegrationBddTest.java, kafka-testing/src/test/resources/kafka/consume/e2e_bdd/test_kafka_e2e_integration_msg.json, kafka-testing/src/test/resources/kafka/consume/e2e_bdd/test_kafka_e2e_integration_msg.yml, kafka-testing/src/test/resources/kafka/produce/test_kafka_produce_2_records.json, kafka-testing/src/test/resources/kafka_servers/intercept/kafka_brokers.properties, kafka-testing/src/test/resources/kafka_servers/intercept/kafka_intercept_consumer.properties, kafka-testing/src/test/resources/kafka_servers/kafka_test_server_double_key.properties, kafka-testing/src/test/resources/kafka_servers/kafka_test_server_int_key.properties
=> StackOverflow example and minor refactoring

core/src/main/java/org/jsmart/zerocode/core/kafka/helper/KafkaConsumerHelper.java, core/src/main/java/org/jsmart/zerocode/core/kafka/helper/KafkaProducerHelper.java, core/src/main/java/org/jsmart/zerocode/core/kafka/send/KafkaSender.java, core/src/test/java/org/jsmart/zerocode/core/kafka/helper/KafkaProducerHelperTest.java, kafka-testing/pom.xml, kafka-testing/src/test/java/org/jsmart/zerocode/integration/tests/kafka/protobuf/KafkaProtobufTest.java
=> ISSUE-423 Proto validation when missing classType

core/pom.xml, http-testing/pom.xml, junit5-testing/pom.xml, kafka-testing/pom.xml, pom.xml, zerocode-maven-archetype/pom.xml
=> Sonatype Nexus Next Release Done

README.md
=> README Updated (typos)

README.md
#Fixes 433 Fixed minor error in README.md 
Noticed this while going through the readme file for this project
=> ISSUE-433 # Fixed mistake in readme file

core/src/main/java/org/jsmart/zerocode/core/kafka/helper/KafkaConsumerHelper.java, kafka-testing/src/test/java/org/jsmart/zerocode/integration/tests/kafka/consume/KafkaConsumeSeekOffsetTest.java, kafka-testing/src/test/resources/kafka/consume/test_kafka_consume_seek_offset_latest.json
=> ISS-432 Read latest message or messages from a Kafka partition offset

core/pom.xml, http-testing/pom.xml, junit5-testing/pom.xml, kafka-testing/pom.xml, pom.xml, zerocode-maven-archetype/pom.xml
=> Sonatype release

.travis.yml
Added docker login to avoid anonymous docker pull rate limiting.
rate-limiting is improved with authenticated docker users. https://blog.travis-ci.com/docker-rate-limits
=> Docker rate limit fix

http-testing/pom.xml, http-testing/src/test/java/org/jsmart/zerocode/testhelp/tests/MockServerTest.java, http-testing/src/test/resources/localhost_stubs/localhost_REST_fake_end_points_stubs.json
created  PR from original zerocode repo
=> fix mock server issue

.travis.yml
docker login fails in fork repositories due to unavailability of token
PR Branch
=> docker login made optional

core/src/main/java/org/jsmart/zerocode/core/report/ZeroCodeReportGeneratorImpl.java, core/src/test/java/org/jsmart/zerocode/core/report/ZeroCodeReportGeneratorImplTest.java
PR Branch
**https://github.com/lankor/zerocode/tree/ISSUE-477-fix-steps-order**
The unexpected behavior is described [here](https://github.com/authorjapps/zerocode/issues/477)
=> ISSUE-477 # Fix the step order in the html report

core/src/main/java/org/jsmart/zerocode/core/engine/mocker/RestEndPointMocker.java, core/src/test/java/org/jsmart/zerocode/core/engine/mocker/RestEndPointMockerTest.java
fixes CI fail for https://github.com/authorjapps/zerocode/pull/480
PR Branch
=> Issue 472/implement dynamic rest endpoint matcher

core/pom.xml, http-testing/pom.xml, junit5-testing/pom.xml, kafka-testing/pom.xml, pom.xml, zerocode-maven-archetype/pom.xml
=> Sonatype rel

README.md
This reverts commit 1d4a7439d5f83a202d9a1d44b606aaf455468669.
#	README.md
PR Branch
=> Revert "Knowledge base for easy documentation search"

core/pom.xml, http-testing/pom.xml, junit5-testing/pom.xml, kafka-testing/pom.xml, pom.xml, zerocode-maven-archetype/pom.xml
=> Sonatype release merging to master

core/pom.xml, core/src/main/java/org/jsmart/zerocode/core/engine/tokens/ZeroCodeValueTokens.java, core/src/main/java/org/jsmart/zerocode/core/utils/TokenUtils.java, core/src/test/java/org/jsmart/zerocode/core/utils/TokenUtilsTest.java, http-testing/pom.xml, junit5-testing/pom.xml, kafka-testing/pom.xml, pom.xml, zerocode-maven-archetype/pom.xml
=> Global Unique and random number - Issue 549

core/src/main/java/org/jsmart/zerocode/core/engine/listener/TestUtilityListener.java, core/src/main/java/org/jsmart/zerocode/core/kafka/consume/ConsumerLocalConfigs.java, core/src/main/java/org/jsmart/zerocode/core/kafka/helper/KafkaConsumerHelper.java, core/src/main/java/org/jsmart/zerocode/core/kafka/receive/ConsumerCommonConfigs.java, core/src/main/java/org/jsmart/zerocode/core/kafka/receive/KafkaReceiver.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodePackageRunner.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeUnitRunner.java, core/src/test/java/org/jsmart/zerocode/core/kafka/DeliveryDetailsTest.java, core/src/test/java/org/jsmart/zerocode/core/kafka/consume/ConsumerLocalConfigsWrapTest.java, core/src/test/java/org/jsmart/zerocode/core/kafka/helper/KafkaConsumerHelperTest.java, docker/compose/shutdown.sh, kafka-testing/src/test/java/org/jsmart/zerocode/integration/tests/kafka/KafkaSuite.java, kafka-testing/src/test/java/org/jsmart/zerocode/integration/tests/kafka/consume/latest/KafkaConsumeLatestExistingTopicTest.java, kafka-testing/src/test/java/org/jsmart/zerocode/integration/tests/kafka/consume/latest/KafkaConsumeLatestTest.java, kafka-testing/src/test/java/org/jsmart/zerocode/integration/tests/kafka/produce/KafkaProduceToPartitionTest.java, kafka-testing/src/test/resources/kafka/consume/latest/test_kafka_produce_consume_only_new_msg.json, kafka-testing/src/test/resources/kafka/consume/latest/test_kafka_produce_consume_only_new_msg_existing_topic.json, kafka-testing/src/test/resources/kafka/consume/latest/test_offset_to_latest_all_partitions.json, kafka-testing/src/test/resources/kafka/consume/latest/test_offset_to_latest_all_partitions_existing_topic.json, kafka-testing/src/test/resources/kafka/produce/test_kafka_produce_to_partition.json, kafka-testing/src/test/resources/kafka_servers/kafka_consumer_latest.properties, kafka-testing/src/test/resources/kafka_servers/kafka_test_server_latest.properties, pom.xml
PR Branch
* [ x] Unit tests added
* [ x] Integration tests added
* [x ] Test names are meaningful
* [x ] Feature manually tested
* [x ] No 'package.*' in the imports
* [ x] Not applicable. The changes did not affect HTTP automation flow
* [x ] Kafka test added to `kafka-testing` module(if applicable) ?
=> Kafka consumer cache

core/src/main/java/org/jsmart/zerocode/core/engine/validators/ZeroCodeValidator.java, core/src/main/java/org/jsmart/zerocode/core/engine/validators/ZeroCodeValidatorImpl.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImpl.java, core/src/test/java/org/jsmart/zerocode/core/engine/validators/ZeroCodeValidatorImplTest.java, core/src/test/java/org/jsmart/zerocode/core/utils/SmartUtilsTest.java, core/src/test/resources/unit_test_files/engine_unit_test_jsons/16_test_validators_jsonpath_expressions_support.json, kafka-testing/src/test/java/org/jsmart/zerocode/integration/tests/kafka/consume/KafkaConsumeJsonTest.java, kafka-testing/src/test/resources/kafka/consume/test_kafka_consume_support_of_jsonpath_in_validators.json
Close #436
PR Branch
See issue #436 discussions
=> fix(validators): support of Zerocode expressions and jsonpath

core/src/main/java/org/jsmart/zerocode/core/di/main/ApplicationMainModule.java, core/src/main/java/org/jsmart/zerocode/core/domain/Step.java, core/src/main/java/org/jsmart/zerocode/core/engine/sorter/SortOrder.java, core/src/main/java/org/jsmart/zerocode/core/engine/sorter/ZeroCodeSorter.java, core/src/main/java/org/jsmart/zerocode/core/engine/sorter/ZeroCodeSorterImpl.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImpl.java, core/src/test/java/org/jsmart/zerocode/core/engine/sorter/ZeroCodeSorterImplTest.java, core/src/test/java/org/jsmart/zerocode/core/utils/SmartUtilsTest.java, core/src/test/java/org/jsmart/zerocode/integrationtests/SorterTest.java, core/src/test/resources/integration_test_files/helloworld/get_api_integration_sorted_response_STRICT_test.json, core/src/test/resources/simulators/test_purpose_end_points.json, core/src/test/resources/unit_test_files/engine_unit_test_jsons/17_scenario_with_sort.json, kafka-testing/src/test/java/org/jsmart/zerocode/integration/tests/kafka/consume/sorting/KafkaSortingTest.java, kafka-testing/src/test/resources/kafka/consume/sorting/test_kafka_sort_records_by_json_path.json
[Link issue](https://github.com/authorjapps/zerocode/issues/555)
PR Branch
**https://github.com/ihorsas/zerocode/tree/issue-555_sorting**
=> Issue 555: Sort message list or array for deterministic assertions

core/pom.xml, http-testing/pom.xml, junit5-testing/pom.xml, kafka-testing/pom.xml, pom.xml, zerocode-maven-archetype/pom.xml
=> New Release 20230406

core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeAssertionsProcessorImpl.java, core/src/main/java/org/jsmart/zerocode/core/utils/FieldTypeConversionUtils.java, core/src/test/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeAssertionsProcessorImplTest.java, core/src/test/java/org/jsmart/zerocode/core/utils/FieldTypeConversionUtilsTest.java, core/src/test/resources/integration_test_files/type_cast/cast_types_to_int_bool_test.json, core/src/test/resources/simulators/test_purpose_end_points.json, core/src/test/resources/unit_test_files/test_engine/02_2_resolve_typecast_in_single_dimention_arraylist_assertion.json
=> PR - Issue 568 typecast fix for 1D array or list

core/pom.xml, http-testing/pom.xml, junit5-testing/pom.xml, kafka-testing/pom.xml, pom.xml, zerocode-maven-archetype/pom.xml
=> PR - Release 20230609

pom.xml
=> ISSUE-589 # Duplicate dependency for protobuf-java in pom.xml

http-testing/pom.xml, http-testing/src/test/java/org/jsmart/zerocode/testhelp/tests/helloworldfileupload/HelloWorldFileUploadTest.java, http-testing/src/test/java/org/jsmart/zerocode/testhelp/tests/helloworldjavaexec/SecurityHeaderTokenDynamicTest.java, http-testing/src/test/java/org/jsmart/zerocode/testhelp/tests/helloworldproperties/HelloWorldPropertiesReadingTest.java, http-testing/src/test/resources/helloworld_file_upload/hello_world_file_upload_test.json, http-testing/src/test/resources/helloworld_file_upload/textfile.txt, http-testing/src/test/resources/postman_echo_host.properties
PR Branch
**https://github.com/wojdeb/zerocode/tree/FileUpload**
Issue #591 - User had a problem with uploading files by API - I've created this example to help users with creating such test cases.
=> added helloworld example of upload files using POST

core/src/test/java/org/jsmart/zerocode/core/utils/TokenUtilsTest.java
=> added unit test cases

BUILDING.md, core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeAssertionsProcessor.java, core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeAssertionsProcessorImpl.java, core/src/main/java/org/jsmart/zerocode/core/engine/tokens/ZeroCodeValueTokens.java, core/src/main/java/org/jsmart/zerocode/core/logbuilder/ZerocodeCorrelationshipLogger.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImpl.java, core/src/main/java/org/jsmart/zerocode/core/utils/TokenUtils.java, core/src/test/java/org/jsmart/zerocode/core/utils/TokenUtilsTest.java, core/src/test/java/org/jsmart/zerocode/integrationtests/masked/MaskedSecretsInMemoryTest.java, core/src/test/resources/integration_test_files/masked/bearer_token_or_secret_masked_reuse_example_.json, core/src/test/resources/integration_test_files/masked/password_or_secrets_masked_in_log_n_console.json, core/src/test/resources/simulators/test_purpose_end_points.json
=> ISSUES-603 Secrets not logged but used for API executions

core/src/test/resources/integration_test_files/masked/bearer_token_or_secret_masked_reuse_example_.json, docker/compose/kafka-schema-registry-m3.yml
=> PR - Simple Kafka compose without KSQL

core/pom.xml, core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeAssertionsProcessorImpl.java, core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeParameterizedProcessorImpl.java, core/src/main/java/org/jsmart/zerocode/core/httpclient/BasicHttpClient.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodePackageRunner.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeUnitRunner.java, core/src/main/java/org/jsmart/zerocode/core/utils/SmartUtils.java, http-testing/pom.xml, junit5-testing/pom.xml, kafka-testing/pom.xml, pom.xml, zerocode-maven-archetype/pom.xml
=> PR - gpg plugin version updated

core/pom.xml, junit5-testing/pom.xml, pom.xml
PR Branch
https://github.com/baulea/zerocode/tree/upgrade_junit
- upgrade multiple maven dependencies for later Java17 compatibility, Issue https://github.com/authorjapps/zerocode/issues/607
- resolve vulnerability [CVE-2020-15250](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-15250) in JUnit 4.12
=> Upgrade to JUnit 4.13.2, consolidate org.jsmart:micro-simulator to 1.1.10

core/src/main/java/org/jsmart/zerocode/core/zzignored/mocking/WireMockJsonContentTesting.java
=> PR - Shorten Mock URL(Tech Debt)

core/src/main/java/org/jsmart/zerocode/core/kafka/helper/KafkaConsumerHelper.java, core/src/main/java/org/jsmart/zerocode/core/kafka/receive/KafkaReceiver.java, docker/compose/kafka-schema-registry.yml, kafka-testing/src/test/java/org/jsmart/zerocode/integration/tests/kafka/consume/KafkaConsumeSeekOffsetTest.java, kafka-testing/src/test/resources/kafka/consume/test_kafka_consume_seek_epoch_continue_from_last_offset.json, kafka-testing/src/test/resources/kafka/consume/test_kafka_consume_seek_epoch_multi_partition.json, kafka-testing/src/test/resources/kafka/consume/test_kafka_consume_seek_epoch_retry.json, kafka-testing/src/test/resources/kafka/consume/test_kafka_consume_seek_timestamp_continue_from_last_offset.json, kafka-testing/src/test/resources/kafka/consume/test_kafka_consume_seek_timestamp_multi_partition.json
fixes #645, #633
PR Branch
Fixed issues in the CI where creation of multiple partition topics was not working correctly.
Handled edge cases around the seek timestamp mechanism and added more tests to verify the same.
=> seek kafka improvements, CI fixed

.github/pull_request_template.md
=> PR - Update pull_request_template.md

kafka-testing/pom.xml
protoc fix from Google. CI is Green now ✅ 
PR Branch
=> PR - issue-652 Protoc fix from Google

core/pom.xml, http-testing/pom.xml, junit5-testing/pom.xml, kafka-testing/pom.xml, pom.xml, zerocode-maven-archetype/pom.xml
- [ Answer] CSV Header Feature added
Note:
This is a release PR only. No features were added or removed.
> Only version bumped to the next one
=> PR - Sonatype release 20240705

core/pom.xml, http-testing/pom.xml, junit5-testing/pom.xml, kafka-testing/pom.xml, pom.xml, zerocode-maven-archetype/pom.xml
```xml
<dependency>
<groupId>org.jsmart</groupId>
<artifactId>zerocode-tdd</artifactId>
<version>1.3.45</version>
</dependency>
```
https://central.sonatype.com/artifact/org.jsmart/zerocode-tdd/1.3.45
ISSUE-680 # Move DB SQL Executor scenario tests to the integrationtests package
#698 by javiertuya was merged Feb 10, 2025 • Approved
Add theme toggle in HTML report
#697 by bppdanto-t was merged Nov 29, 2024 • Approved
ISSUE-689 # Sanitize json report file name
#692 by javiertuya was merged Oct 27, 2024 • Approved
ISSUE-688 # Propagate exceptions from java api operations
#690 by javiertuya was merged Oct 25, 2024 • Approved
ISSUE-680 # Add the DB SQL Executor to import data from CSV and execute SQL statements
#686 by javiertuya was merged Dec 22, 2024 • Approved
Fixed flaky test-case: …
=> Sonatype release 20250415 (version 1.3.45)

core/pom.xml, core/src/main/java/org/jsmart/zerocode/core/db/DbCsvLoader.java, core/src/main/java/org/jsmart/zerocode/core/db/DbSqlExecutor.java, core/src/main/java/org/jsmart/zerocode/core/di/module/CsvParserModule.java, core/src/main/java/org/jsmart/zerocode/core/di/provider/CsvParserConfig.java, core/src/main/java/org/jsmart/zerocode/core/di/provider/CsvParserInterface.java, core/src/main/java/org/jsmart/zerocode/core/di/provider/CsvParserProvider.java, core/src/main/java/org/jsmart/zerocode/core/di/provider/JacksonCsvParserAdapter.java, core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeParameterizedProcessorImpl.java, core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImpl.java, core/src/test/java/org/jsmart/zerocode/core/db/DbCsvLoaderTest.java, core/src/test/java/org/jsmart/zerocode/core/di/CsvParserTest.java, core/src/test/java/org/jsmart/zerocode/core/domain/ParameterizedTest.java, core/src/test/java/org/jsmart/zerocode/core/domain/StepTest.java, core/src/test/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeParameterizedProcessorImplTest.java, pom.xml
- [https://github.com/authorjapps/zerocode/issues/702] Which issue or ticket was(will be) fixed by this PR? (capture the issue number)
PR Branch
**https://github.com/rkampani/zerocode/tree/feature/701-replaceUniVocityJar **
=> Replace uniVocity CSV library with jackson-csv #702
