authorjapps/zerocode

src/main/java/org/jsmart/zerocode/core/domain/reports/ZeroCodeReportProperties.java
src/main/java/org/jsmart/zerocode/core/engine/listener/ZeroCodeTestReportListener.java
src/main/java/org/jsmart/zerocode/core/runner/ZeroCodePackageRunner.java
src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeUnitRunner.java

Gradle issues-
- There are number of tickets opened for this, but not yet fixed.
* - https://discuss.gradle.org/t/testrunfinished-not-run-in-junit-integration/14644
* - https://github.com/gradle/gradle/issues/842
* - many more related tickets.
Gradle does not deal with JUnit listeners.
This PR is to bypass listener and generate reports.
_The usual JUnit xml report is still generated at the usual folder._
But Zerocode extent reports are useful and handy for step recognition and search and filter operation, as well as Chart,CSV format and more...
Hence this fix.
Requested by @BeTheCodeWithYou

ISS-152 - Gradle report

---

core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImpl.java
core/src/test/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunner_FailedAssertions.java
core/src/test/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunner_FailedAssertionsTest.java
core/src/test/java/org/jsmart/zerocode/core/runner/e2e/FailSimpleAssertionInMultiStep.java
core/src/test/resources/19_fail_tests/01_two_step_one_fail.json

PR to fix #241 - Basic Unit test added to verify assertions section is updated on step failure
The implemented code doesn't alter the "happy" path, behaviour is unchanged and only the payload is displayed.
Images below show example outputs in Console, JSON and HTML report.

ISS-241 # Display assumed payload and assertions on step error

---

core/src/main/java/org/jsmart/zerocode/core/engine/assertion/FieldHasDateAfterValueAsserter.java
core/src/main/java/org/jsmart/zerocode/core/engine/assertion/FieldHasDateBeforeValueAsserter.java
core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeJsonTestProcesorImpl.java
core/src/test/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeJsonTestProcesorImplTest.java
core/src/test/resources/date_after_before/dateAfterBefore_test_both.json
core/src/test/resources/date_after_before/dateAfterBefore_test_fail_afterSameDate.json
core/src/test/resources/date_after_before/dateAfterBefore_test_fail_beforeSameDate.json
core/src/test/resources/date_after_before/dateAfterBefore_test_fail_both.json
http-testing/src/test/java/org/jsmart/zerocode/testhelp/tests/helloworlddateafterbefore/HelloWorldDateAfterBeforeTest.java
http-testing/src/test/resources/helloworld_date/hello_world_date_after_before_test.json

PR to add functionality for issue #5. Added 4 test cases to _ZeroCodeJsonTestProcesorImplTest.java_ to test 'after' and 'before' conditions. Added 1 example test case to _http-testing_ module.

ISS-5 # Add date.after and date.before assertions

---

README.md
core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeJsonTestProcesorImpl.java
core/src/test/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeJsonTestProcesorImplTest.java
core/src/test/resources/date_after_before/dateAfterBefore_test_both.json
core/src/test/resources/date_after_before/dateAfterBefore_test_fail_afterSameDate.json
core/src/test/resources/date_after_before/dateAfterBefore_test_fail_beforeSameDate.json
core/src/test/resources/date_after_before/dateAfterBefore_test_fail_both.json
http-testing/src/test/resources/helloworld_date/hello_world_date_after_before_test.json

Update assertion tokens '$DATE.BEFORE' and '$DATE.AFTER' introduced in issue #5 to be more specific and uniform with the rest of the project. 
$DATE.BEFORE    ->     $LOCAL.DATETIME.BEFORE
$DATE.AFTER       ->     $LOCAL.DATETIME.AFTER

ISS-5 # Update datetime after/before assertion token to 'local.datetime'

---

core/src/main/java/org/jsmart/zerocode/core/engine/assertion/FieldIsOneOfValueAsserter.java
core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeJsonTestProcesorImpl.java
core/src/test/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeJsonTestProcesorImplTest.java
core/src/test/resources/one_of/oneOf_test_currentStatus.json
core/src/test/resources/one_of/oneOf_test_emptyString.json
core/src/test/resources/one_of/oneOf_test_expectedArrayEmpty.json
core/src/test/resources/one_of/oneOf_test_whiteSpace.json

Added $ONE.OF vanilla case functionality for issue #67 with tests. Empty string values and whitespace values are also supported (for example if actual result is a single whitespace and one of the expected values is a whitespace, the test will pass).
Second PR to fix issue caused by a reference to a Java 11 method in FieldIsOneOfValueAsserter.java (String.isBlank()) in previous PR

ISS-67 # Add '$ONE.OF:' functionality 

---

README.md
core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeTokens.java
core/src/main/java/org/jsmart/zerocode/core/utils/TokenUtils.java
core/src/test/java/org/jsmart/zerocode/core/utils/TokenUtilsTest.java
http-testing/src/test/java/org/jsmart/zerocode/testhelp/tests/helloworldtokenresolver/HelloWorldTokenResolverTest.java
http-testing/src/test/resources/helloworld_token_resolving/helloworld_token_resolving_ok.json

Fix for #248 
If the property cannot be resolved (Specified property does not exist) then the token is not replaced and remains as a normal string.
For the positive test case I used property `java,vendor` as this should be present on all machines.

ISS-248 # Added System Property Token placeholder

---

core/src/main/java/org/jsmart/zerocode/core/engine/mocker/RestEndPointMocker.java
core/src/test/java/org/jsmart/zerocode/core/engine/mocker/RestEndPointMockerTest.java
core/src/test/resources/integration_test_files/wiremock_integration/wiremock_end_point_json_body.json

updated junit test for PATCH,
updated test scenario json with PATCH example

ISS-310 - [IN PROGRESS] added PATCH support for mock maker

---

.travis.yml

Travis has removed the oracle-jdk-8 and defaults to jdk-11 by default which resulted in a build failure.
Due to Oracles new licensing changes oracle-jdk-8 cannot be installed, hence switched to open-jdk-8
REF:
https://github.com/travis-ci/travis-ci/issues/10290#issuecomment-432331802
https://travis-ci.community/t/install-of-oracle-jdk-8-failing/3038

fix travis ci build failure

---

README.md

ISSUE-357 # Fix readme typo (`Lenient` -> `Linient`)
PR Branch
https://github.com/stevenwaterman/zerocode/tree/patch-1
The readme contains a typo. According to the docs at https://github.com/authorjapps/zerocode/wiki#lenient-and-strict-matching, the verification modes are `STRICT` and `LENIENT`, but the first example in the `Matchers` section uses `LINIENT`.
None relevant

Fix typo in example matcher

---

core/pom.xml

[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …

[SECURITY] Use HTTPS to resolve dependencies in Maven Build

---

core/src/main/java/org/jsmart/zerocode/core/engine/mocker/RestEndPointMocker.java
core/src/test/java/org/jsmart/zerocode/core/engine/mocker/RestEndPointMockerTest.java
core/src/test/resources/integration_test_files/wiremock_integration/mock_via_wiremock_then_test_the_end_point.json

Curently, the content-type header is malformed `Content-Type: "application/json"`, it should be `Content-Type: application/json`
close #346

ISSUE-346 # fix content type response with wiremock

---

core/src/main/java/org/jsmart/zerocode/core/di/provider/GsonSerDeProvider.java
core/src/main/java/org/jsmart/zerocode/core/kafka/helper/KafkaConsumerHelper.java
core/src/main/java/org/jsmart/zerocode/core/kafka/helper/KafkaProducerHelper.java
core/src/main/java/org/jsmart/zerocode/core/kafka/helper/ProducerRecordBuilder.java
core/src/main/java/org/jsmart/zerocode/core/kafka/receive/message/ConsumerJsonRecord.java
core/src/main/java/org/jsmart/zerocode/core/kafka/send/KafkaSender.java
core/src/main/java/org/jsmart/zerocode/core/kafka/send/message/ProducerJsonRecord.java
core/src/test/java/org/jsmart/zerocode/core/kafka/helper/KafkaConsumerHelperTest.java
core/src/test/java/org/jsmart/zerocode/core/kafka/helper/ProducerRecordBuilderTest.java
core/src/test/java/org/jsmart/zerocode/core/kafka/receive/message/ConsumerJsonRecordTest.java
core/src/test/java/org/jsmart/zerocode/core/kafka/send/message/ProducerJsonRecordsTest.java
core/src/test/java/org/jsmart/zerocode/core/kafka/send/message/ProducerRawRecordsTest.java
kafka-testing/src/test/java/org/jsmart/zerocode/integration/tests/kafka/KafkaSuite.java
kafka-testing/src/test/java/org/jsmart/zerocode/integration/tests/kafka/produce/KafkaProduceRawWithHeadersTest.java
kafka-testing/src/test/java/org/jsmart/zerocode/integration/tests/kafka/produce/KafkaProduceWithHeadersTest.java
kafka-testing/src/test/resources/kafka/produce/test_kafka_produce_json_with_headers.json
kafka-testing/src/test/resources/kafka/produce/test_kafka_produce_raw_with_headers.json

PR Branch
https://github.com/Cyril-Edme/zerocode/tree/ISS-330-send-headers-while-producing-to-kafka
We should be able to send some headers in our Kafka message. As well as the consumer should be able to assert on the received headers.

Iss 330 send headers while producing to kafka

---

core/src/main/java/org/jsmart/zerocode/core/kafka/helper/KafkaConsumerHelper.java
core/src/main/java/org/jsmart/zerocode/core/kafka/receive/KafkaReceiver.java
core/src/test/java/org/jsmart/zerocode/core/kafka/helper/KafkaConsumerHelperTest.java
kafka-testing/src/test/resources/kafka/consume/test_kafka_consume.json

[Link to Branch
](https://github.com/ddingel/zerocode/tree/fix-issue-421-KafkaReceiver)
In a kafka consume step, on the first poll, a consumer group join will be triggered. 
This can take multiple seconds to complete. Currently we use will use our maxNoOfRetryPollsOrTimeouts in that time.
If the consumer group join has not finished we return without any result or meaningful message.
The proposed change will move the initial poll out of the loop.
Additionally if the initial poll fails an exception will be thrown.
* [ X] Unit tests added
* [ X] Test names are meaningful
* [ X] Feature manually tested
* [ X] No 'package.*' in the imports
* [X ] Not applicable. The changes did not affect HTTP automation flow
* [ X] Kafka test added to `kafka-testing` module(if applicable) ?

Fix issue 421 kafka receiver

---

core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeExternalFileProcessorImpl.java
core/src/test/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeExternalFileProcessorImplTest.java
core/src/test/resources/unit_test_files/filebody_unit_test/common/common_content_recursive.json
core/src/test/resources/unit_test_files/filebody_unit_test/json_step_test_file_recursive.json
http-testing/src/test/java/org/jsmart/zerocode/testhelp/tests/helloworldextjsonfile/HelloReuseJsonFileAsContentTest.java
http-testing/src/test/resources/helloworld_ext_file_json/hello_world_jsonfile_as_request_body_with_inner_ref.json
http-testing/src/test/resources/reusable_content/request/request_body_with_address.json

#453  Use reusable json file inside another json file
PR Branch
https://github.com/RDBreed/zerocode/tree/453-Use-JSON-file-within-a-reusable-JSON-file
"As Automation Engineer I want to be able to reference a reusable JSON file from another reusable JSON file."
Am committing in the context of **Hacktoberfest**. Hope I can help and feel free when you need any further help!
* [] Not applicable. The changes did not affect HTTP automation flow

#453 - Use reusable json file inside another json file

---

core/src/main/java/org/jsmart/zerocode/core/engine/executor/ApiServiceExecutor.java
core/src/main/java/org/jsmart/zerocode/core/engine/executor/ApiServiceExecutorImpl.java
core/src/main/java/org/jsmart/zerocode/core/kafka/client/BasicKafkaClient.java
core/src/main/java/org/jsmart/zerocode/core/kafka/send/KafkaSender.java
core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImpl.java
kafka-testing/src/main/java/org/jsmart/zerocode/kafka/MyCustomKafkaClient.java
kafka-testing/src/test/java/org/jsmart/zerocode/integration/tests/kafka/produce/file/KafkaProduceSyncFromFileJsonTest.java
kafka-testing/src/test/resources/kafka/pfiles/test_data_json_with_vars.json
kafka-testing/src/test/resources/kafka/produce/file_produce/test_kafka_produce_sync_from_file_json_with_ref.json

#451 Sending dynamic headers (values) to kafka while reading records from file
PR Branch
https://github.com/RDBreed/zerocode/tree/451-send-dynamic-headers-to-kafka-in-records
Because I had this ready and not sure if anyone else would pick this up, just created a PR...
I am trying to get some PRs in the context of **Hacktoberfest**, so please tag it when you feel it is okay. Thanks for looking into this! 👍 
* [x ] Not applicable. The changes did not affect HTTP automation flow
* [] Not applicable. The changes did not affect Kafka automation flow

#451 send dynamic headers to kafka in records

---

core/src/main/java/org/jsmart/zerocode/core/kafka/helper/KafkaConsumerHelper.java
core/src/main/java/org/jsmart/zerocode/core/kafka/receive/KafkaReceiver.java
core/src/test/java/org/jsmart/zerocode/core/kafka/helper/KafkaConsumerHelperTest.java
kafka-testing/src/test/java/org/jsmart/zerocode/integration/tests/kafka/consume/KafkaConsumePollingTest.java
kafka-testing/src/test/resources/kafka_servers/kafka_test_server_polling.properties

PR Branch
https://github.com/dandalavinod/zerocode/tree/issue462-polltimeout-kafkajoin
Intial poll of the kafka consumer group is currently waiting for 500ms which in some cases, where there are network latency or broker throughput issues, fail with kafka consumer fail to join in time. 
The fix is to make the intial poll duration wait configurable to use the consumer.pollingTime field set in the properties file and if this property is not set then will default to current 500ms poll duration
* [ x] Unit tests added
updated existing unit tests to fit and behave per the changes added.
* [x ] Test names are meaningful
* [ x] Feature manually tested
Tested manually against my environment where i encountered the problem and as i use the configurable setting of consumer.pollingTime=1000 ; the …

ISSUE-462 # fix poll time out to intial consumer group join

---

BUILDING.md
core/src/main/java/org/jsmart/zerocode/core/domain/builders/ExtentReportsFactory.java
core/src/main/java/org/jsmart/zerocode/core/engine/listener/ZeroCodeTestReportListener.java
kafka-testing/src/test/java/org/jsmart/zerocode/integration/tests/more/ksql/KafkaKsqlTest.java
kafka-testing/src/test/resources/kafka/consume/ksql/test_ksql_query.json
kafka-testing/src/test/resources/kafka/consume/negative/test_kafka_rest_proxy_avro_msg_wrong_value.json
pom.xml

PR Branch
#527 
When running a zerocode (1.3.28) project under a Mac M1 chip, the following error is throw:
```
org.apache.kafka.common.KafkaException: org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=Mac and os.arch=aarch64
```
This is a limitation from the `snappy-java` (1.1.7.2) in the `kafka-client` 2.1.0 version;
This limitation is solved since the `1.1.8.2` version but not patched in the `kafka-client` 2.1 branch (see https://github.com/apache/kafka/blob/2.1/gradle/dependencies.gradle)

fix: update snappy-java for m1 support

---

core/src/main/java/org/jsmart/zerocode/core/engine/executor/httpapi/HttpApiExecutorImpl.java
core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImpl.java
http-testing/src/test/resources/logback.xml
kafka-testing/src/test/resources/logback.xml

- Removed few more WARN to reduce noice
PR Branch

PR-580 More prettyfied logging for a Scenario

---

.gitignore
core/pom.xml
http-testing/pom.xml
junit5-testing/pom.xml
kafka-testing/pom.xml
pom.xml
zerocode-maven-archetype/pom.xml

PR - Release 20230930

---

core/src/main/java/org/jsmart/zerocode/core/httpclient/utils/FileUploadUtils.java
core/src/test/java/org/jsmart/zerocode/core/utils/FileUploadUtilsTest.java

PR Branch
MASTER
https://github.com/authorjapps/zerocode/issues/401

Issue 401 # corrected string casting

---

README.md
core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeAssertionsProcessor.java
core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeAssertionsProcessorImpl.java
core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeExternalFileProcessorImpl.java
core/src/main/java/org/jsmart/zerocode/core/engine/tokens/ZeroCodeValueTokens.java
core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImpl.java
core/src/main/java/org/jsmart/zerocode/core/utils/SmartUtils.java
core/src/test/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeAssertionsProcessorImplTest.java
core/src/test/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeExternalFileProcessorImplTest.java
core/src/test/resources/integration_test_files/filebody/hello_world_file_request_n_response.json
core/src/test/resources/simulators/test_purpose_end_points.json
core/src/test/resources/unit_test_files/json_content_unit_test/json_step_no_json_content_test.json
core/src/test/resources/unit_test_files/json_content_unit_test/json_step_test_json_content.json
core/src/test/resources/unit_test_files/json_content_unit_test/json_step_test_json_content_array.json
core/src/test/resources/unit_test_files/json_content_unit_test/json_step_test_json_content_block.json
core/src/test/resources/unit_test_files/json_content_unit_test/json_step_test_json_content_objectarray.json
core/src/test/resources/unit_test_files/json_content_unit_test/json_step_test_wrong_json_path.json
http-testing/src/test/java/org/jsmart/zerocode/testhelp/tests/helloworldjsoncontent/HelloJsonContentAsBodyTest.java
http-testing/src/test/resources/helloworld_json_content/hello_world_json_content_as_request_body.json

Fixes Issue: https://github.com/authorjapps/zerocode/issues/601
PR Branch

ISSUE-601 # Resolve JSON.CONTENT as object or array

---

core/src/main/java/org/jsmart/zerocode/core/constants/ZeroCodeReportConstants.java
core/src/main/java/org/jsmart/zerocode/core/report/ZeroCodeReportGeneratorImpl.java
core/src/test/java/org/jsmart/zerocode/core/report/ZeroCodeReportGeneratorImplTest.java

issues-616 Authors and hashtags aka categories

---

core/src/main/java/org/jsmart/zerocode/core/engine/executor/javaapi/JavaMethodExecutorImpl.java
http-testing/src/main/java/org/jsmart/zerocode/zerocodejavaexec/SampleMethods.java
http-testing/src/test/java/org/jsmart/zerocode/testhelp/tests/helloworldjavaexec/MultipleArgumentMethodExecTest.java
http-testing/src/test/java/org/jsmart/zerocode/testhelp/tests/helloworldjavaexec/StaticMethodExecTest.java
http-testing/src/test/resources/helloworldjavaexec/java_method_multiple_arguments_test.json
http-testing/src/test/resources/helloworldjavaexec/java_static_method_test.json

1. Support for multiple parameters in java method exec
2. Support for static method Exec
3. Minor refactoring changes
fixes #622 , #626 
[PR Branch](https://github.com/a1shadows/zerocode/tree/issue-622/static-method-support)
With this PR, it will be possible to do java exec of static methods as well as methods with multiple arguments.
For static methods, they have to be invoked in exactly the same way as instance methods were invoked up to this point.
As for methods with multiple arguments, let's say there is a method like so
```
public Map<String, String> sampleMultiArgMethod1(String arg1, String arg2)
```
It would be invoked in the following way:
```
{
"name": "sample method 1",
"url": "org.jsmart.zerocode.zerocodejavaexec.SampleMethods",
"method": "sampleMultiArgMethod1",
"request": { …
```

ISSUE-622, ISSUE-626 Java static method and multiple arguments exec support

---

core/pom.xml
core/src/main/java/org/jsmart/zerocode/core/domain/builders/ExtentReportsFactory.java
http-testing/pom.xml
junit5-testing/pom.xml
kafka-testing/pom.xml
pom.xml

PR Branch
**_[here](https://github.com/baulea/zerocode/tree/maven_dependencies)_**
upgrade multiple maven dependencies for later Java17 compatibility
#607

Maven dependencies

---

core/src/main/java/org/jsmart/zerocode/core/kafka/helper/KafkaProducerHelper.java
core/src/test/java/org/jsmart/zerocode/core/engine/assertion/NumberComparatorTest.java
core/src/test/java/org/jsmart/zerocode/core/engine/executor/javaapi/JavaMethodExecutorImplTest.java
core/src/test/java/org/jsmart/zerocode/core/runner/ZeroCodeUnitRuntimeAnnoTest.java

PR Branch
**_[pull request](https://github.com/baulea/zerocode/tree/java17)_**
#598

ISSUE-598 # remove maven-compiler warnings with target Java 17 (JDK8 Compatible)

---

.github/workflows/main.yml
core/src/main/java/org/jsmart/zerocode/core/kafka/helper/KafkaConsumerHelper.java
docker/compose/kafka-schema-registry.yml
kafka-testing/src/test/resources/kafka/consume/test_kafka_consume_seek_epoch_and_timestamp.json

Fixes #631 
PR Branch
If there are partitions for which there is no valid offset corresponding to the timestamp to seek to, the offsetForTimestamp method still includes it in the Map returned, but with a NULL value. We need to skip all partitions that have offset as NULL when subscribing to avoid an error when we try to seek to the offset at a later step.

Fix for seekTo feature

---

core/pom.xml
core/src/main/java/org/jsmart/zerocode/core/engine/mocker/RestEndPointMocker.java
core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeParameterizedProcessorImpl.java
core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImpl.java
junit5-testing/pom.xml
pom.xml

PR Branch
https://github.com/baulea/zerocode/tree/upgrade_velocity-engine-core
- upgrade multiple maven dependencies for later Java17 compatibility, Issue https://github.com/authorjapps/zerocode/issues/607
- resolve vulnerability [CVE-2020-13936](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-13936) in org.apache.velocity:velocity:1.7

Upgrade to org.apache.velocity:velocity-engine-core:2.3

---

core/src/main/resources/logback.xml
http-testing/src/main/resources/logback.xml
http-testing/src/test/resources/logback.xml
junit5-testing/pom.xml
junit5-testing/src/main/resources/logback.xml
kafka-testing/src/main/resources/logback.xml
kafka-testing/src/test/resources/logback.xml
pom.xml

PR Branch
https://github.com/baulea/zerocode/tree/upgrade_logback
- upgrade multiple maven dependencies for later Java17 compatibility, Issue https://github.com/authorjapps/zerocode/issues/607
- logback 1.0.7 has vulnerabilities, which are removed in 1.3.14: https://mvnrepository.com/artifact/ch.qos.logback/logback-classic
This also solves https://github.com/authorjapps/zerocode/pull/533 and https://github.com/authorjapps/zerocode/pull/499

upgrade logback from 1.0.7 to 1.3.14 and slf4j to 2.0.12

---

core/src/main/java/org/jsmart/zerocode/core/di/module/CsvParserModule.java
core/src/main/java/org/jsmart/zerocode/core/di/module/GsonModule.java
core/src/main/java/org/jsmart/zerocode/core/di/module/HttpClientModule.java
core/src/main/java/org/jsmart/zerocode/core/di/module/ObjectMapperModule.java
core/src/main/java/org/jsmart/zerocode/core/di/provider/CsvParserProvider.java
core/src/main/java/org/jsmart/zerocode/core/di/provider/DefaultGuiceHttpClientProvider.java
core/src/main/java/org/jsmart/zerocode/core/di/provider/GsonSerDeProvider.java
core/src/main/java/org/jsmart/zerocode/core/di/provider/ObjectMapperProvider.java
core/src/main/java/org/jsmart/zerocode/core/di/provider/YamlObjectMapperProvider.java
core/src/main/java/org/jsmart/zerocode/core/domain/MockStep.java
core/src/main/java/org/jsmart/zerocode/core/domain/Parameterized.java
core/src/main/java/org/jsmart/zerocode/core/domain/Step.java
core/src/main/java/org/jsmart/zerocode/core/runner/ZeroCodeMultiStepsScenarioRunnerImpl.java
core/src/test/java/org/jsmart/zerocode/core/domain/ScenarioSpecTest.java
core/src/test/java/org/jsmart/zerocode/core/engine/mocker/RestEndPointMockerTest.java
core/src/test/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeParameterizedProcessorImplTest.java
pom.xml

partially fixes #607 
resolves #642 
PR Branch
Notable changes include 
1. adding null checks to JsonNodes because recent Jackson versions deserialize null values to Java null instead of Jackson NullNode
2. Moving from javax.inject to jakarta.inject with latest Guice version

Upgrading Jackson, Guice, Guava and jsonassert

---

core/pom.xml
core/src/main/java/org/jsmart/zerocode/core/di/provider/JsonPathJacksonProvider.java
core/src/main/java/org/jsmart/zerocode/core/engine/assertion/array/ArrayIsEmptyAsserterImpl.java
core/src/main/java/org/jsmart/zerocode/core/engine/assertion/array/ArraySizeAsserterImpl.java
core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeAssertionsProcessorImpl.java
core/src/main/java/org/jsmart/zerocode/core/engine/sorter/ZeroCodeSorterImpl.java
core/src/main/java/org/jsmart/zerocode/core/engine/validators/ZeroCodeValidatorImpl.java
core/src/main/java/org/jsmart/zerocode/core/kafka/helper/KafkaProducerHelper.java
core/src/test/java/org/jsmart/zerocode/converter/MimeTypeConverterTest.java
core/src/test/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeAssertionsProcessorImplTest.java
core/src/test/java/org/jsmart/zerocode/core/engine/sorter/ZeroCodeSorterImplTest.java
core/src/test/java/org/jsmart/zerocode/core/engine/validators/ZeroCodeValidatorImplTest.java
pom.xml

PR Branch
https://github.com/baulea/zerocode/tree/jsonPathJacksonProvider
Move to jackson json provider in JsonPath instead of jsonsmart. Jackson is already used in zerocode, and we can get rid of jsonsmart as another JSON processor.

introduce JsonPathJacksonProvider

---

core/pom.xml
core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeExternalFileProcessorImpl.java
http-testing/pom.xml
junit5-testing/pom.xml
kafka-testing/pom.xml
pom.xml
zerocode-maven-archetype/pom.xml

PR - Sonatype release 20240430

---

.github/workflows/main.yml

Install docker compose manually and try

---

core/src/test/java/org/jsmart/zerocode/core/kafka/receive/message/ConsumerJsonRecordTest.java

authorjapps/zerocode/issues/685
PR Branch
**[fork](https://github.com/hermya/zerocode)**
ConsumerJsonRecordTest.should_serialize_a_record_with_headers is a flaky test, fixed in this PR.
POINT OF FAILURE -> random attribute ordering in hashmap
Fixed using NonDex pugin
Suggested command to check all flaky tests :
> mvn nondex:nondex
For particular test:
Add the following lines to your pom.xml
```
<plugin> 
<groupId>edu.illinois</groupId>
<artifactId>nondex-maven-plugin</artifactId>
<version>2.1.7</version>
</plugin>
```
and run
>mvn -pl ./core nondex:nondex -Dtest=org.jsmart.zerocode.core.kafka.receive.message.ConsumerJsonRecordTest#should_serialize_a_record_with_headers -DnondexRuns=10
**OR**
>mvn -pl ./core edu.illinois:nondex-maven-plugin:2.1.7:nondex …

Fixed flaky test-case: ConsumerJsonRecordTest.should_serialize_a_record_with_headers

---

core/src/main/java/org/jsmart/zerocode/core/AddService.java
core/src/main/java/org/jsmart/zerocode/core/engine/executor/javaapi/JavaMethodExecutorImpl.java
core/src/test/java/org/jsmart/zerocode/core/engine/executor/javaapi/JavaMethodExecutorImplTest.java
core/src/test/resources/unit_test_files/java_apis/03_test_json_java_service_method_Exception.json

PR Branch
**https://github.com/javiertuya/zerocode/tree/688-exceptions-java-api**
When executing a java method that is invoked by the java api as an operation, any exception in the java method should be shown in the stacktrace to facilitate debugging. The executor exception handler should include this exception

ISSUE-688 # Propagate exceptions from java api operations

---

core/src/main/java/org/jsmart/zerocode/core/domain/builders/ZeroCodeIoWriteBuilder.java
core/src/main/java/org/jsmart/zerocode/core/utils/SmartUtils.java
core/src/test/java/org/jsmart/zerocode/core/utils/SmartUtilsTest.java

PR Branch
**https://github.com/javiertuya/zerocode/tree/689-report-scenario-invalid-chars**
To generate html reports, a json file is created for each scenario. The file name is taken from the scenario name. Report for this scenario fails if the name contains characters that are not allowed as part of a filename. This PR sanitizes the report file name.
Note to reviewers: Sanitization is strict (only keeps alphanumeric, spaces, dots and dashes) because the report filenames are guaranteed to be unique because they contain the correlation id. It could be less strict by replacing only the windows forbidden characters (also valid for unix), even making different replacements for linux and windows, but I'm not sure if it's worth it.

ISSUE-689 # Sanitize json report file name

---

core/src/main/java/org/jsmart/zerocode/core/constants/ZeroCodeReportConstants.java
core/src/main/java/org/jsmart/zerocode/core/domain/builders/ExtentReportsFactory.java

PR Branch
https://github.com/bppdanto-t/zerocode/tree/add-theme-toggle
Due to version update of `extentreport` library, the toggle theme icon is missing from the HTML report. While toggling the theme is still achievable by pressing "L" key with keyboard, there's not much visibility to the user on how to do it. This PR will add the toggle icon back and move it to the top right side, as requested by @authorjapps ([comment link](https://github.com/authorjapps/zerocode/issues/694#issuecomment-2506364661)).
Light theme
Dark theme

Add theme toggle in HTML report

---

.github/workflows/main.yml
core/pom.xml
core/src/main/java/org/jsmart/zerocode/core/db/DbCsvLoader.java
core/src/main/java/org/jsmart/zerocode/core/db/DbCsvRequest.java
core/src/main/java/org/jsmart/zerocode/core/db/DbSqlExecutor.java
core/src/main/java/org/jsmart/zerocode/core/db/DbSqlRequest.java
core/src/main/java/org/jsmart/zerocode/core/db/DbSqlRunner.java
core/src/main/java/org/jsmart/zerocode/core/db/DbValueConverter.java
core/src/test/java/org/jsmart/zerocode/core/db/DbCsvLoaderTest.java
core/src/test/java/org/jsmart/zerocode/core/db/DbSqlExecutorScenarioPostgresTest.java
core/src/test/java/org/jsmart/zerocode/core/db/DbSqlExecutorScenarioTest.java
core/src/test/java/org/jsmart/zerocode/core/db/DbSqlRunnerTest.java
core/src/test/java/org/jsmart/zerocode/core/db/DbTestBase.java
core/src/test/java/org/jsmart/zerocode/core/db/DbValueConverterTest.java
core/src/test/resources/db_test.properties
core/src/test/resources/db_test_postgres.properties
core/src/test/resources/integration_test_files/db/db_csv_load_with_headers.json
core/src/test/resources/integration_test_files/db/db_csv_load_with_headers_postgres.json
core/src/test/resources/integration_test_files/db/db_csv_load_without_headers.json
core/src/test/resources/integration_test_files/db/db_sql_execute.json
core/src/test/resources/integration_test_files/db/db_sql_execute_postgres.json
core/src/test/resources/integration_test_files/db/players_with_headers.csv
core/src/test/resources/integration_test_files/db/players_without_headers.csv
docker/compose/pg_compose.yml
pom.xml

PR Branch
**https://github.com/javiertuya/zerocode/tree/680-db-sql-executor**
Documentation at PR https://github.com/authorjapps/zerocode-tdd-docs/pull/24
This PR provides an out of the box component that uses the Java API to execute steps that interact with a database.
The executor class `org.jsmart.zerocode.core.db.DbSqlExecutor` provides two operations:
- `EXECUTE`: Run a SQL statement to verify the data stored in the database or insert/update in the data.
- `LOADCSV`: Load the contents of a CSV file located in the resources folder into a table.
Acceptance critera fulfillment:
- AC1, AC2, AC5, AC6: Done, with unit and integration tests, H2 database.
- AC3: Done, PostgreSQL: the same unit and integration tests were executed in local, not in CI
- AC4: Partially done, read CSV files from …

ISSUE-680 # Add the DB SQL Executor to import data from CSV and execute SQL statements

---

core/src/test/java/org/jsmart/zerocode/core/kafka/DeliveryDetailsTest.java

This pull request addresses a flaky test, `DeliveryDetailsTest.testSerDeser`, in the `zerocode` project. The test was failing intermittently due to assumptions about the ordering of JSON fields during serialization and deserialization.
The `DeliveryDetailsTest.testSerDeser` test relied on strict JSON field ordering during serialization. Gson, the JSON library used in the project, does not guarantee field order by default. This caused the test to fail when the field order changed, especially under NonDex shuffling, which explores non-deterministic behaviors.
Run the test with NonDex to simulate shuffling of field order:
```bash
mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex -pl core -Dtest=org.jsmart.zerocode.core.kafka.DeliveryDetailsTest#testSerDeser
```
Before the fix, the test …

Fix flaky test in DeliveryDetailsTest

---

.github/workflows/main.yml
core/pom.xml
core/src/main/java/org/jsmart/zerocode/core/di/module/OptionalTypeAdapter.java
core/src/main/java/org/jsmart/zerocode/core/di/module/OptionalTypeAdapterFactory.java
core/src/main/java/org/jsmart/zerocode/core/di/provider/GsonSerDeProvider.java
core/src/main/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeAssertionsProcessorImpl.java
core/src/main/java/org/jsmart/zerocode/core/kafka/helper/KafkaConsumerHelper.java
core/src/main/java/org/jsmart/zerocode/core/utils/HelperJsonUtils.java
core/src/test/java/org/jsmart/zerocode/core/db/DbCsvLoaderTest.java
core/src/test/java/org/jsmart/zerocode/core/db/DbSqlRunnerTest.java
core/src/test/java/org/jsmart/zerocode/core/db/DbTestBase.java
core/src/test/java/org/jsmart/zerocode/core/db/DbValueConverterTest.java
core/src/test/java/org/jsmart/zerocode/core/di/ApplicationMainModuleBackwordCompatibilityTest.java
core/src/test/java/org/jsmart/zerocode/core/di/ApplicationMainModuleTest.java
core/src/test/java/org/jsmart/zerocode/core/di/CsvParserTest.java
core/src/test/java/org/jsmart/zerocode/core/domain/ParameterizedTest.java
core/src/test/java/org/jsmart/zerocode/core/domain/ScenarioSpecTest.java
core/src/test/java/org/jsmart/zerocode/core/domain/StepTest.java
core/src/test/java/org/jsmart/zerocode/core/domain/ValidatorTest.java
core/src/test/java/org/jsmart/zerocode/core/engine/executor/httpapi/ApiServiceExecutorImplTest.java
core/src/test/java/org/jsmart/zerocode/core/engine/mocker/RestEndPointMockerTest.java
core/src/test/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeAssertionsProcessorImplTest.java
core/src/test/java/org/jsmart/zerocode/core/engine/preprocessor/ZeroCodeParameterizedProcessorImplTest.java
core/src/test/java/org/jsmart/zerocode/core/guice/ZeroCodeGuiceTestRule.java
core/src/test/java/org/jsmart/zerocode/core/utils/SmartUtilsTest.java
kafka-testing/src/test/resources/kafka/produce/negative/test_kafka_produce_from_worng_filename.json
pom.xml

PR Branch
Zerocode generates a Java 8 Jar, but issues when running under higher JDKs have been detected. This PR addresses this:
- JDK Compatibility: Minor tweaks were made and maven profiles defined to prevent test and build failures.
- Tested with all current JDK LTSs: 8, 11, 17, 21
- Jukito to Guice: Swapped Jukito for Guice to ensure compatibility with newer JDKs and ease future upgrades.
- Type Reference Fixes: Adjusted methods to handle stricter type enforcement in newer JDKs, preventing errors.
- Gson Optional Support: Added a custom TypeAdapter for java.util.Optional to enable proper JSON serialization/deserialization.

Error in running the zerocode tests in JDK23/21 #704

---

.github/workflows/main.yml

PR Branch
[javiertuya:714-multiple-jdks](https://github.com/javiertuya/zerocode/tree/714-multiple-jdks)
After merging #713 the build supports Java versions from 8 to 23, but future changes could break compatibility if no tested in CI. This PR includes:
- Use a matrix strategy to run the workflow on all LTS JDK versions (8,11,17,21) and the latest (23)
- Add downloadable junit test reports
- Workflow updates (java distribution, actions, docker compose, maven cache)

Build multiple JDKs and junit test reports
